apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ameijboom.com
build:
  artifacts:
    - image: frontend
      context: frontend
      docker:
        buildArgs: {}

  local:
    useBuildkit: true
