apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ameijboom.com
deploy:
  helm:
    releases:
      - name: helm
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        version: 0.1.0
